### ISSUE TITLE
Docker image alerta/alerta-web:5.2.4 run alerta-server 5.2.3

### ISSUE THREAD

**Issue by ehidden** [alerta/docker-alerta#70]
Docker image alerta/alerta-web:5.2.4 run alerta-server 5.2.3  
See below the result of pip freeze in alerta-web:5.2.4 container 

`docker run -ti --rm --name alerta  --entrypoint "bash" alerta/alerta-web:5.2.4`
`alerta@1b466c311dae:/$ source venv/bin/activate`
`(venv) alerta@1b466c311dae:/$ pip freeze | grep "alerta"`
`alerta==5.2.0`
`alerta-server==5.2.3`

is this expected behaviour ?

**Comment by satterly** [comment]
No, this is a bug with how github and docker are integrated. It's broken and Docker can't/won't fix it. I have to manually update the version number instead of it just pulling the latest and this can result it there being inconsistencies if the build is triggered at the wrong time. I've kicked off a new build of 5.2.4 and hopefully that should fix it. Thanks for reporting. I'll keep an eye on this in future.

**Comment by ehidden** [comment]
Thanks @satterly 
It appears that the new container image still have the version 5.2.3 of alerta-server.
For the moment, i'll build my own alerta-web image based on alerta-server 5.2.4
